- alias: Grace
  name: Grace Zhang
  role: Lab manager and aspiring veterinarian
  email: zhang.gfei@gmail.com
  avatar: graceZhang_bio.jpg
  bio: "Grace was our lab manager in 2015/2016, and is now a Vet student at Virginia Tech.  During her time in the lab, Grace was instrumental in managing our canine clincial trial on inflammatory bowel disease"

- alias: Kevin
  name: Kevin O'Brian
  role: UPenn Veterinary Student
  email: kevinob@vet.upenn.edu
  avatar: KevinOBrian.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "Kevin is a rising 2nd year vet student at PennVet with an interest in exploring the relationship between the gut microbiome and canine health.  Kevin spent much of the summer of 2016 in the lab and handled all aspects of one of our largest microbiome studies -- a longitudinal profile of the gut microbiome in sows throughout pregnancy"

- alias: amisic
  name: Ana M. Misic
  role: Post-doctoral Scientist
  email: a.misic@gmail.com
  twitter: 
  phone: +1-215-898-9911
  fax: +1-215-746-2295
  avatar: ana_bio.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "My research uses DNA sequencing technologies (Illumina, PacBio, Oxford Nanopore) to answer questions about bacteria that are important to human and animal health. My research interests include human and animal pathogens, antimicrobial resistance, and horizontal gene transfer. My favorite bacteria are Staphylococcus schleiferi and Pseudomonas aeruginosa."

- alias: Ying
  name: Ying Chen
  role: Lab Volunteer
  email: ying8@upenn.edu
  avatar: YingChen.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "My research interests include using high-throughput sequencing technologies and computational tools to tackle a broad range of questions for the lab and CHMI collaborators."

- alias: Francislon
  name: Francislon Silva Oliveira
  role: Ph.D. student; Brazilian 'sandwich' program
  email: francislon@gmail.com
  twitter: francislon
  avatar: francislon.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "Bioinformatics developer and passionate about science. My current research is focused on exploring the microbiome world through new data visualization analysis tools."

- alias: Elaine
  name: 
  role: Visiting scholar 
  email: francislon@gmail.com
  twitter: francislon
  avatar: francislon.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "Bioinformatics developer and passionate about science. My current research is focused on exploring the microbiome world through new data visualization analysis tools."

- alias: Jake
  name: Jake Leiby
  role: Rotating graduate student (GCB)
  email: jleiby@pennmedicine.upenn.edu
  phone: 
  twitter: LeibyJacob
  avatar: jake.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "I am interested in microbial genomics, infectious disease, and whole genome sequencing."

- alias: Amanda
  name: Amanda Finck
  role: Rotating graduate student (IGG)
  email: finckam@pennmedicine.upenn.edu
  phone: 
  twitter: FinckAmanda
  avatar: amanda.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: I am studying infection-induced gut dysbiosis using RNA-sequencing in order to discover novel interactions between the microbiome and host immune signaling. My broader interests include leveraging both single cell and bulk ‘omics approaches to better understand the immune system.
