- alias: Grace
  name: Grace Zhang
  role: Lab manager and aspiring veterinarian
  email: zhang.gfei@gmail.com
  avatar: graceZhang_bio.jpg
  bio: "Grace was our lab manager in 2015/2016, and is now a Vet student at Virginia Tech.  During her time in the lab, Grace was instrumental in managing our canine clincial trial on inflammatory bowel disease"

- alias: Kevin
  name: Kevin O'Brian
  role: UPenn Veterinary Student
  email: kevinob@vet.upenn.edu
  avatar: KevinOBrian.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "Kevin is a rising 2nd year vet student at PennVet with an interest in exploring the relationship between the gut microbiome and canine health.  Kevin spent much of the summer of 2016 in the lab and handled all aspects of one of our largest microbiome studies -- a longitudinal profile of the gut microbiome in sows throughout pregnancy"

- alias: amisic
  name: Ana M. Misic
  role: Post-doctoral Scientist
  email: a.misic@gmail.com
  twitter: 
  phone: +1-215-898-9911
  fax: +1-215-746-2295
  avatar: ana_bio.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "My research uses DNA sequencing technologies (Illumina, PacBio, Oxford Nanopore) to answer questions about bacteria that are important to human and animal health. My research interests include human and animal pathogens, antimicrobial resistance, and horizontal gene transfer. My favorite bacteria are Staphylococcus schleiferi and Pseudomonas aeruginosa."

- alias: Ayah
  name: Ayah El-Fahmawi
  role: Undergraduate researcher
  email: ayahe@sas.upenn.edu
  phone: +1-215-898-9911
  fax: +1-215-746-2295
  avatar: ayah_bio.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "I am a freshman studying biology at UPenn who is excited to learn more about research, microbiology, and bioinformatics while gaining lab experience.  My project in the lab is focused on understanding the mechanisms by which intestinal inflammation leads to dysbiosis and severe disease"
