- alias: Grace
  name: Grace Zhang
  role: Lab manager and aspiring veterinarian
  email: zhang.gfei@gmail.com
  avatar: graceZhang_bio.jpg
  bio: "Grace was our lab manager in 2015/2016, and is now a Vet student at Virginia Tech.  During her time in the lab, Grace was instrumental in managing our canine clincial trial on inflammatory bowel disease"

- alias: Kevin
  name: Kevin O'Brian
  role: UPenn Veterinary Student
  email: kevinob@vet.upenn.edu
  avatar: KevinOBrian.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "Kevin is a rising 2nd year vet student at PennVet with an interest in exploring the relationship between the gut microbiome and canine health.  Kevin spent much of the summer of 2016 in the lab and handled all aspects of one of our largest microbiome studies -- a longitudinal profile of the gut microbiome in sows throughout pregnancy"

- alias: Ying
  name: Ying Chen
  role: Lab Volunteer
  email: ying8@upenn.edu
  avatar: YingChen.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "I am a computational biology graduate student at UPenn and a volunteer in the lab. My research interests include using high-throughput sequencing technologies and computational tools to study serum biomarkers of disease subtypes and progress of human cutaneous Leishmaniasis."
