- alias: Dan
  name: Daniel Beiting
  role: Assistant Professor of Pathobiology
  twitter: hostmicrobe
  github: dpbisme
  web: hostmicrobe.org
  avatar: dan2.jpg
  email: danielbeiting@gmail.com
  phone: +1-215-898-9247
  address: University of Pennsylvania, Rm 314 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "I am an immunologist using 'omics approaches to interrogate the host-pathogen interface."

- alias: Shuai
  name: Shuai Wang
  role: Visiting Scholar
  email: wshuai@upenn.edu
  avatar: shuai.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "My research employs genome sequencing and comparative genomic methods to explore the biology, evolution and host-parasite interface of some medically important parasites. My current study focuses on interactions between host intestinal microbiome and the parasite Toxoplasma gondii"

- alias: Elise
  name: Elise Krespan
  role: Research Specialist
  email: ekrespan@vet.upenn.edu
  phone: +1-215-898-9911
  twitter: 
  avatar: elise.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "In addition to general lab management, I work with investigators to plan, develop and manage high-throughput sequencing projects, ranging from transcriptome studies, single-cell seq, 16S rRNA profiling and shotgun metagenomics."

- alias: Camila
  name: Camila Farias Amorim
  role: Postdoctoral researcher
  email: camilafarias112@gmail.com
  phone: 215-898-0526
  twitter: 
  avatar: camila.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "My interests center mainly around using high-throughput sequencing to study the human immune response during cutaneous leishmaniasis."

- alias: Alex
  name: Alex Berry
  role: Postdoctoral researcher
  email: berrya@sas.upenn.edu
  phone: 
  twitter: alex_berry14
  avatar: alex.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "I am interested in using population genetic and phylogenetic approaches to understand how parasites affect the microbiome."

- alias: Jake
  name: Jake Leiby
  role: Rotating graduate student (GCB)
  email: jleiby@pennmedicine.upenn.edu
  phone: 
  twitter: LeibyJacob
  avatar: jake.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio:

- alias: Amanda
  name: Amanda Finck
  role: Rotating graduate student (IGG)
  email: finckam@pennmedicine.upenn.edu
  phone: 
  twitter: FinckAmanda
  avatar: amanda.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio:
