- alias: Dan
  name: Daniel Beiting
  role: Assistant Professor; Technical Director
  twitter: hostmicrobe
  github: dpbisme
  web: hostmicrobe.org
  avatar: headshot.jpg
  email: danielbeiting@gmail.com
  phone: +1-215-898-9247
  fax: +1-215-746-2295
  address: University of Pennsylvania, Rm 314 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "I am an immunologist using 'omics approaches to interrogate the host-pathogen interface."

- alias: Shuai
  name: Shuai Wang
  role: Visiting Scholar
  email: wshuai@upenn.edu
  avatar: shuai.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "My research employs genome sequencing and comparative genomic methods to explore the biology, evolution and host-parasite interface of some medically important parasites. My current study focuses on interactions between host intestinal microbiome and the parasite Toxoplasma gondii"

- alias: Megan
  name: Megan Sullivan
  role: Research Specialist
  email: mcsull@vet.upenn.edu
  phone: +1-215-898-9911
  twitter: 
  avatar: megan.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: 

- alias: Camila
  name: Camila Farias Amorim
  role: Postdoctoral researcher
  email: camilafarias112@gmail.com
  phone: 215-594-9806
  twitter: 
  avatar: camila.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "My interests center mainly around using high-throughput sequencing to study the human immune response during cutaneous leishmaniasis."

- alias: Ayah
  name: Ayah El-Fahmawi
  role: Undergraduate researcher
  email: ayahe@sas.upenn.edu
  phone: +1-215-898-9911
  fax: +1-215-746-2295
  avatar: ayah_bio.jpg
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "I am a senior studying biology at UPenn and I've been working to elucidate the mechanisms by which intestinal inflammation leads to dysbiosis and severe disease"

- alias: Alex
  name: Alex Berry
  role: Postdoctoral researcher
  email: berrya@sas.upenn.edu
  phone: 
  twitter: 
  avatar: 
  address: University of Pennsylvania, Rm 380 Hill Pavilion, School of Veterinary Medicine, 380 S. University Ave., Philadelphia, PA 19104-4539 USA
  bio: "I'm interested in applying population genetics to microbiome data."
